version: "3.8"

services:
  web:
    build: .
    container_name: oldschool-service
    ports:
      - "9080:80"
    volumes:
      - oldschool-grades:/service/grades
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '2'

  db:
    image: mysql:8.0
    volumes:
      - oldschool-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: oldschool
      MYSQL_USER: oldschool
      MYSQL_PASSWORD: oldschoolpassword

volumes:
  oldschool-db:
  oldschool-grades:
