version: '3.8'

services:
  web:
    build: .
    container_name: oldschool-service
    ports:
      - '9080:80'
    volumes:
      - oldschool-db:/service/db
      - oldschool-grades:/service/grades
volumes:
  oldschool-db:
  oldschool-grades: